baseURL = "https://balabharathijayaraman.com"
languageCode = "en-us"
title = "Learn with Balabharathi Jayaraman"
[params]
    linkedinURL="https://www.linkedin.com/in/balabharathijayaraman"
    fbURL="https://www.facebook.com/noisyboyelan"
    twitterURL="https://twitter.com/balabharathijay"